client_id = "b0b65072439310f0c015fa3d90d75b92"
name = "Bitsy-YMM-EO"
application_url = "https://bitsy-ymm-eo.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes"

[auth]
redirect_urls = [ 
  "https://bitsy-ymm-eo.vercel.app/api/install",
  "https://bitsy-ymm-eo.vercel.app/api/auth-callback"
]